import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToolBar from './components/ToolBar'
import SideBar from './components/SideBar'
import shorts from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-zinc-900 text-zinc-200'>
        <div className='flex flex-col border-2 border-green-500 h-screen'>
         <ToolBar />
         <div className='flex border-2 border-blue-500 flex-1'>
          <SideBar />
        {children}
         </div>
        </div>
      </body>
    </html>
  )
}
